GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [eFront] TO [Role_Service_Account];
Go
GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [stg_eFront] TO [Role_Service_Account];
Go
GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [history_eFront] TO [Role_Service_Account];
Go
GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA :: [rpt_eFront] TO [Role_Service_Account];


