--GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA ::[rpt_eFront] TO [rpt_eFront];
--GO
--GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA ::[eFront] TO [eFront];
--GO
--GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA ::[stg_eFront] TO [stg_eFront];
--GO
--GRANT SELECT, INSERT, ALTER, UPDATE, DELETE, EXECUTE ON SCHEMA ::[history_eFront] TO [history_eFront];
--GO
--GRANT SELECT  ON SCHEMA ::[rpt_eFront] TO [Role_PowerUsers];
--GO
--GRANT SELECT ON SCHEMA ::[eFront] TO [Role_PowerUsers];
--GO
--GRANT SELECT ON SCHEMA ::[history_eFront] TO [Role_PowerUsers];